services:
  frontend-ui:
    build:
      context: ./
    ports:
      - "3000:3000"
    container_name: frontend-ui
    stdin_open: true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env
    networks:
      - my-network


  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/prod:/etc/nginx/conf.d
    networks:
      - my-network



networks:
  my-network:
