export const paths = {
  HOME: '/',
  REDIRECT: '*',
  ABOUT: 'about-us',
  LOGIN: 'login',
  SIGNUP: 'signup',
  CART: 'cart',
  ORDERS: 'orders',
  CATEGORY: 'category',
  BEST: 'best',
  CUSTOMER_HELP: 'customer-help',
  REVIEW: 'review',
  CONTACT: 'contact-us',
  NEWS: 'news',
  FAQ: 'faq',
  CONSULTATION: 'consultation',
  CUSTOMER_POST: 'costumer-post',
  PRODUCT: 'product/:id',
  CHECK_OUT: 'checkout',
  CHECK_OUT_ONE: 'first',
  CHECK_OUT_SECOND: 'second',
  CHECK_OUT_THIRD: 'third',
  CHECK_OUT_FOURTH: 'fourth',
  SINGLE_NEW: 'news/:id',
  CONSULTATION_INFO: 'consultation/:id',
  USER: 'user',
  ORDER_HISTORY: 'order-history',
  USER_PROFILE: 'profile',
  POINTS: 'points',
  QUESTIONS: 'questions',
  USER_REVIEWS: 'reviews',
  EDIT_PROFILE: 'edit-profile',
  CHANGE_PASSWORD: "change-password",
  WRITE_REVIEW: "write-review"
};

export const modalPaths = {
  CONSULTATION: 'consultation',
  REVIEW: 'review',
  ORDER: 'order'
}